# This is a basic workflow to help you get started with Actions

name: Final release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version in semantic versioning format (i.e. 1.0.2)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Running release"

      - name: Run a multi-line script
        run: |
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
            https://api.github.com/repos/gersonnoboa/glia-core/actions/workflows/schedule.yml/enable
