# This is a basic workflow to help you get started with Actions

name: Schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          #!/usr/bin/env bash

          LATEST_VERSION=$(curl \
            -X GET \
            https://search.maven.org/solrsearch/select\?q\=g:com.glia+AND+a:android-widgets\&core\=gav\&rows\=2\&wt\=json \
            | jq -r '.response.docs[0].v|tostring'
            )

          echo $LATEST_VERSION

          GITHUB_RELEASE_TAG=$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
            https://api.github.com/repos/gersonnoboa/glia-core/releases?per_page=1 \
            | jq -r '.[0].tag_name'
          )

          echo $GITHUB_RELEASE_TAG

          if [ $LATEST_VERSION = $GITHUB_RELEASE_TAG ]
          then
            echo "Equal"
            curl \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.API_TOKEN_GITHUB }}" \
              https://api.github.com/repos/gersonnoboa/glia-core/actions/workflows/schedule.yml/disable
          else
            echo "Not equal"
          fi
