# This is a basic workflow to help you get started with Actions

name: Schedule

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          LATEST_VERSION=$(curl \
            -X GET \
            https://search.maven.org/solrsearch/select\?q\=g:com.glia+AND+a:android-widgets\&core\=gav\&rows\=2\&wt\=json \
            | jq '.response.docs[0].v'
          )
          echo $LATEST_VERSION
